import { library } from '@fortawesome/fontawesome-svg-core';

import {
  faBell,
  faHeart as farHeart,
  faBookmark as farBookmark,
  faThumbsUp,
  faComment,
  faCircleDown as farCircleDown,
  faEye as farEye,
  faSquarePlus as farSquarePlus,
  faFolderOpen as farFolderOpen,
  faFolderClosed as farFolderClosed,
  faFolder as farFolder,
  faTrashCan,
} from '@fortawesome/free-regular-svg-icons';

import {
  faCaretDown,
  faChevronDown,
  faAngleDown,
  faEllipsis,
  faHeart as fasHeart,
  faBookmark as fasBookmark,
  faBriefcase,
  faBuilding,
  faDiagramProject,
  faAngleRight,
  faCircleDown as fasCircleDown,
  faEye as fasEye,
  faAngleLeft,
  faSquarePlus as fasSquarePlus,
  faFolderOpen as fasFolderOpen,
  faFolderClosed as fasFolderClosed,
  faFolderPlus,
  faPlus,
  faMagnifyingGlass,
  faArrowLeft,
  faEllipsisVertical,
  faFolder as fasFolder,
  faFolderMinus,
  faPaperPlane,
} from '@fortawesome/free-solid-svg-icons';

// Add all icons to the library
library.add(
  faBell,
  faCaretDown,
  faChevronDown,
  faAngleDown,
  faEllipsis,
  farHeart,
  fasHeart,
  farBookmark,
  fasBookmark,
  faBriefcase,
  faBuilding,
  faDiagramProject,
  faThumbsUp,
  faComment,
  faAngleRight,
  farCircleDown,
  fasCircleDown,
  farEye,
  fasEye,
  faAngleLeft,
  farSquarePlus,
  fasSquarePlus,
  farFolderOpen,
  fasFolderOpen,
  farFolderClosed,
  fasFolderClosed,
  faFolderPlus,
  faPlus,
  faMagnifyingGlass,
  faArrowLeft,
  faEllipsisVertical,
  fasFolder,
  farFolder,
  faFolderMinus,
  faTrashCan,
  faPaperPlane
);
